In [22]:
import pandas as pd
import numpy as np
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
data=pd.read_pickle(r"C:\Users\user\Downloads\Projet ML\Model1(KNN)\Données nettoyées\fusion_final.pkl.gz")
data

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
13089,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
13090,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
13091,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
13092,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
13093,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [24]:
data.head()

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."

In [25]:
data.isnull().sum()

tconst               0
titleType            0
primaryTitle         0
originalTitle        0
startYear            0
runtimeMinutes       0
genres               0
French_Title      5571
averageRating        0
numVotes             0
primaryName       2174
dtype: int64

In [26]:
#Nombre de valeurs en double
data['tconst'].duplicated().sum()

772

In [27]:
#Supprimer ces valeurs en double
data = data.drop_duplicates(subset = "tconst")

In [28]:
# Réindexer le DataFrame après la suppression des doublons
data = data.reset_index(drop=True)

In [29]:
data

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"Léonce Perret,Louis Leubas,Maurice Lagrenée,Ém..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"Stacia Napierkowska,Musidora,Édouard Mathé,Mar..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"Lillian Gish,Robert Harron,Mae Marsh,F.A. Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"René Cresté,Musidora,René Poyen,Édouard Mathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"Norman Selby,Lillian Gish,Richard Barthelmess,..."
...,...,...,...,...,...,...,...,...,...,...,...
12317,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,Arjun Das,George Maryan"
12318,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
12319,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
12320,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"Herman Finkers,Johanna ter Steege,Leonie ter B..."
12321,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12322 entries, 0 to 12321
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tconst          12322 non-null  object
 1   titleType       12322 non-null  object
 2   primaryTitle    12322 non-null  object
 3   originalTitle   12322 non-null  object
 4   startYear       12322 non-null  int64
 5   runtimeMinutes  12322 non-null  float64
 6   genres          12322 non-null  object
 7   French_Title    6751 non-null   object
 8   averageRating   12322 non-null  float64
 9   numVotes        12322 non-null  float64
 10  primaryName     10195 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 1.0+ MB

In [31]:
#Remove space
def remove_space(text):
    if isinstance(text, str):  # Vérifier si le texte est une chaîne de caractères
        return text.replace(" ", "")
    else:
        return text  # Retourner la valeur sans modification si ce n'est pas une chaîne de caractères

In [32]:
data['primaryName']=data['primaryName'].apply(remove_space)
data['genres']=data['genres'].apply(remove_space)

In [33]:
data

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124.0,"Crime,Drama",L'Enfant de Paris (1913),7.2,446.0,"LéoncePerret,LouisLeubas,MauriceLagrenée,Émile..."
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421.0,"Action,Adventure,Crime",Les vampires (1915),7.3,5398.0,"StaciaNapierkowska,Musidora,ÉdouardMathé,Marce..."
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163.0,"Drama,History",Intolérance (1916),7.7,16642.0,"LillianGish,RobertHarron,MaeMarsh,F.A.Turner"
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300.0,"Adventure,Crime",Judex (1916),7.2,1117.0,"RenéCresté,Musidora,RenéPoyen,ÉdouardMathé"
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90.0,"Drama,Romance",Le lys brisé (1919),7.2,11014.0,"NormanSelby,LillianGish,RichardBarthelmess,Don..."
...,...,...,...,...,...,...,...,...,...,...,...
12317,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145.0,"Action,Crime,Drama",Kaithi (2019),8.4,42096.0,"Karthi,Narain,ArjunDas,GeorgeMaryan"
12318,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125.0,"Documentary,Sport",NaN,8.1,501.0,NaN
12319,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111.0,Drama,NaN,7.6,680.0,NaN
12320,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103.0,"Comedy,Drama",De Beentjes van Sint-Hildegard (2020),7.4,3306.0,"HermanFinkers,JohannaterSteege,LeonieterBraak,..."
12321,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130.0,Drama,NaN,8.5,380.0,NaN

In [34]:
data['genres'] = data['genres'].str.replace(',', ' ')
data['primaryName'] = data['primaryName'].str.replace(',', ' ')
data['runtimeMinutes'] = data['runtimeMinutes'].astype(int)
data['runtimeMinutes'] = data['runtimeMinutes'].astype(str)
data

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124,Crime Drama,L'Enfant de Paris (1913),7.2,446.0,LéoncePerret LouisLeubas MauriceLagrenée Émile...
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421,Action Adventure Crime,Les vampires (1915),7.3,5398.0,StaciaNapierkowska Musidora ÉdouardMathé Marce...
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163,Drama History,Intolérance (1916),7.7,16642.0,LillianGish RobertHarron MaeMarsh F.A.Turner
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300,Adventure Crime,Judex (1916),7.2,1117.0,RenéCresté Musidora RenéPoyen ÉdouardMathé
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90,Drama Romance,Le lys brisé (1919),7.2,11014.0,NormanSelby LillianGish RichardBarthelmess Don...
...,...,...,...,...,...,...,...,...,...,...,...
12317,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145,Action Crime Drama,Kaithi (2019),8.4,42096.0,Karthi Narain ArjunDas GeorgeMaryan
12318,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125,Documentary Sport,NaN,8.1,501.0,NaN
12319,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111,Drama,NaN,7.6,680.0,NaN
12320,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103,Comedy Drama,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,HermanFinkers JohannaterSteege LeonieterBraak ...
12321,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130,Drama,NaN,8.5,380.0,NaN

In [35]:
# Convertir  les colonnes en chaînes de caractères
data['genres'] = data['genres'].astype(str)
data['primaryName'] = data['primaryName'].astype(str)
data['runtimeMinutes'] = data['runtimeMinutes'] + 'min'
data['startYear']=data['startYear'].astype(str)
# Appliquer la transformation pour créer la colonne 'tags'
data['tags'] = data.apply(lambda row: ' '.join(row['genres'].split(',')) + ' ' + ' '.join(row['primaryName'].split(',')) + ' ' + row['runtimeMinutes'] + ' ' + row['startYear'], axis=1)

In [36]:
data

,tconst,titleType,primaryTitle,originalTitle,startYear,runtimeMinutes,genres,French_Title,averageRating,numVotes,primaryName,tags
0,tt0003883,movie,L'enfant de Paris (1913),L'enfant de Paris (1913),1913,124min,Crime Drama,L'Enfant de Paris (1913),7.2,446.0,LéoncePerret LouisLeubas MauriceLagrenée Émile...,Crime Drama LéoncePerret LouisLeubas MauriceLa...
1,tt0006206,movie,Les vampires (1915),Les vampires (1915),1915,421min,Action Adventure Crime,Les vampires (1915),7.3,5398.0,StaciaNapierkowska Musidora ÉdouardMathé Marce...,Action Adventure Crime StaciaNapierkowska Musi...
2,tt0006864,movie,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,1916,163min,Drama History,Intolérance (1916),7.7,16642.0,LillianGish RobertHarron MaeMarsh F.A.Turner,Drama History LillianGish RobertHarron MaeMars...
3,tt0006886,movie,Judex (1916),Judex (1916),1916,300min,Adventure Crime,Judex (1916),7.2,1117.0,RenéCresté Musidora RenéPoyen ÉdouardMathé,Adventure Crime RenéCresté Musidora RenéPoyen ...
4,tt0009968,movie,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,1919,90min,Drama Romance,Le lys brisé (1919),7.2,11014.0,NormanSelby LillianGish RichardBarthelmess Don...,Drama Romance NormanSelby LillianGish RichardB...
...,...,...,...,...,...,...,...,...,...,...,...,...
12317,tt9900782,movie,Kaithi (2019),Kaithi (2019),2019,145min,Action Crime Drama,Kaithi (2019),8.4,42096.0,Karthi Narain ArjunDas GeorgeMaryan,Action Crime Drama Karthi Narain ArjunDas Geor...
12318,tt9904844,movie,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),2019,125min,Documentary Sport,NaN,8.1,501.0,nan,Documentary Sport nan 125min 2019
12319,tt9905462,movie,Pengalila (2019),Pengalila (2019),2019,111min,Drama,NaN,7.6,680.0,nan,Drama nan 111min 2019
12320,tt9911196,movie,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),2020,103min,Comedy Drama,De Beentjes van Sint-Hildegard (2020),7.4,3306.0,HermanFinkers JohannaterSteege LeonieterBraak ...,Comedy Drama HermanFinkers JohannaterSteege Le...
12321,tt9911774,movie,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),2019,130min,Drama,NaN,8.5,380.0,nan,Drama nan 130min 2019

In [37]:
data.iloc[8]['tags']

'Drama Fantasy Horror EinarAxelsson VictorSjöström HildaBorgström ToreSvennberg AstridHolm ConcordiaSelander LisaLundholm TorWeijden 107min 1921'

In [38]:
new_data=data[['tconst','primaryTitle','originalTitle','French_Title','tags']]
new_data

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),Crime Drama LéoncePerret LouisLeubas MauriceLa...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),Action Adventure Crime StaciaNapierkowska Musi...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),Drama History LillianGish RobertHarron MaeMars...
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),Adventure Crime RenéCresté Musidora RenéPoyen ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),Drama Romance NormanSelby LillianGish RichardB...
...,...,...,...,...,...
12317,tt9900782,Kaithi (2019),Kaithi (2019),Kaithi (2019),Action Crime Drama Karthi Narain ArjunDas Geor...
12318,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),NaN,Documentary Sport nan 125min 2019
12319,tt9905462,Pengalila (2019),Pengalila (2019),NaN,Drama nan 111min 2019
12320,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),De Beentjes van Sint-Hildegard (2020),Comedy Drama HermanFinkers JohannaterSteege Le...
12321,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),NaN,Drama nan 130min 2019

In [39]:
#Transformer tags en lettre minuscules
new_data['tags']=new_data['tags'].apply(lambda x :x.lower())
new_data

C:\Users\user\AppData\Local\Temp\ipykernel_16132\3890256331.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags']=new_data['tags'].apply(lambda x :x.lower())

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),crime drama léonceperret louisleubas mauricela...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),action adventure crime stacianapierkowska musi...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),drama history lilliangish robertharron maemars...
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),adventure crime renécresté musidora renépoyen ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),drama romance normanselby lilliangish richardb...
...,...,...,...,...,...
12317,tt9900782,Kaithi (2019),Kaithi (2019),Kaithi (2019),action crime drama karthi narain arjundas geor...
12318,tt9904844,Ott Tänak: The Movie (2019),Ott Tänak: The Movie (2019),NaN,documentary sport nan 125min 2019
12319,tt9905462,Pengalila (2019),Pengalila (2019),NaN,drama nan 111min 2019
12320,tt9911196,The Marriage Escape (2020),De beentjes van Sint-Hildegard (2020),De Beentjes van Sint-Hildegard (2020),comedy drama hermanfinkers johannatersteege le...
12321,tt9911774,Padmavyuhathile Abhimanyu (2019),Padmavyuhathile Abhimanyu (2019),NaN,drama nan 130min 2019

In [40]:
new_data.head()

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),crime drama léonceperret louisleubas mauricela...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),action adventure crime stacianapierkowska musi...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),drama history lilliangish robertharron maemars...
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),adventure crime renécresté musidora renépoyen ...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),drama romance normanselby lilliangish richardb...

In [41]:
new_data.to_csv(r"C:\Users\user\Downloads\Projet ML\Model2 textvectorclassificator(countvectorizer)\Dataset1\new_data.csv")

In [42]:
new_data.iloc[8]['tags']

'drama fantasy horror einaraxelsson victorsjöström hildaborgström toresvennberg astridholm concordiaselander lisalundholm torweijden 107min 1921'

# Racinisation (ou stemming) des mots dans un texte donné¶

In [43]:
# Avec l'algorithme Snowball
sb = SnowballStemmer(language='english') # initialisation avec la langue anglaise

In [44]:
def stem(text):
    L = []
    for i in text.split():
        L.append(sb.stem(i))
    string = " ".join(L)
    return string

In [45]:
new_data['tags'] = new_data['tags'].apply(stem)
new_data.head(10)

C:\Users\user\AppData\Local\Temp\ipykernel_16132\55449531.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['tags'] = new_data['tags'].apply(stem)

,tconst,primaryTitle,originalTitle,French_Title,tags
0,tt0003883,L'enfant de Paris (1913),L'enfant de Paris (1913),L'Enfant de Paris (1913),crime drama léonceperret louisleuba mauricelag...
1,tt0006206,Les vampires (1915),Les vampires (1915),Les vampires (1915),action adventur crime stacianapierkowska musid...
2,tt0006864,Intolerance (1916),Intolerance: Love's Struggle Throughout the Ag...,Intolérance (1916),drama histori lilliangish robertharron maemars...
3,tt0006886,Judex (1916),Judex (1916),Judex (1916),adventur crime renécresté musidora renépoyen é...
4,tt0009968,Broken Blossoms (1919),Broken Blossoms or The Yellow Man and the Girl...,Le lys brisé (1919),drama romanc normanselbi lilliangish richardba...
5,tt0010307,J'accuse! (1919),J'accuse (1919),J'accuse (1919),drama horror war romualdjoubé maximedesjardin ...
6,tt0011565,The Penalty (1920),The Penalty (1920),Satan (1920),crime drama thriller charlesclari dorispawn ji...
7,tt0011841,Way Down East (1920),Way Down East (1920),À travers l'orage (1920),drama romanc lilliangish richardbarthelmess mr...
8,tt0012364,The Phantom Carriage (1921),Körkarlen (1921),La charrette fantôme (1921),drama fantasi horror einaraxelsson victorsjöst...
9,tt0012494,Destiny (1921),Der müde Tod (1921),Les Trois Lumières (1921),drama fantasi horror bernhardgoetzk lildagov w...

In [46]:
new_data.iloc[8]['tags']

'drama fantasi horror einaraxelsson victorsjöström hildaborgström toresvennberg astridholm concordiaseland lisalundholm torweijden 107min 1921'

In [47]:
#2nd methode de racinisation
#import nltk
#from nltk.stem import PorterStemmer
#ps = PorterStemmer()
#def stems(text):
#    T = []
    
#    for i in text.split():
#        T.append(ps.stem(i))
    
#    return " ".join(T)

#  Construction du modèle

In [48]:
#Création du modèle
model2 = CountVectorizer(max_features=30000, stop_words='english')
#Entrainer le modèle
vector_matrix = model2.fit_transform(new_data['tags'])
vector_matrix.shape

(12322, 23450)

In [49]:
# Cette ligne affiche le vocabulaire avec les indices correspondants après la vectorisation
print(model2.vocabulary_)

{'crime': 4561, 'drama': 5563, 'léonceperret': 12886, 'louisleuba': 12648, 'mauricelagrené': 14029, 'émilekeppen': 23408, 'marcgérard': 13326, 'henriduv': 8210, 'mariedor': 13519, '124min': 24, '1913': 92, 'action': 478, 'adventur': 623, 'stacianapierkowska': 20253, 'musidora': 15152, 'édouardmathé': 23403, 'marcellévesqu': 13318, 'jeanaymé': 9612, 'fernandherrmann': 6567, '421min': 291, '1915': 93, 'histori': 8380, 'lilliangish': 12417, 'robertharron': 18126, 'maemarsh': 12967, 'turn': 21629, '163min': 64, '1916': 94, 'renécresté': 17837, 'renépoyen': 17848, '300min': 273, 'romanc': 18321, 'normanselbi': 16001, 'richardbarthelmess': 17915, 'donaldcrisp': 5431, 'arthurhoward': 2299, 'edwardpeilsr': 5722, 'georgeberang': 7165, '90min': 315, '1919': 95, 'horror': 8442, 'war': 22439, 'romualdjoubé': 18334, 'maximedesjardin': 14055, 'séverin': 20760, 'mar': 13273, 'angèleguy': 1712, '166min': 67, 'thriller': 21237, 'charlesclari': 3942, 'dorispawn': 5502, 'jimmason': 9909, 'lonchaney': 12578, '1920': 97, 'mrs': 15076, 'davidlandau': 4940, 'lowellsherman': 12675, '145min': 46, 'fantasi': 6440, 'einaraxelsson': 5766, 'victorsjöström': 22039, 'hildaborgström': 8321, 'toresvennberg': 21508, 'astridholm': 2431, 'concordiaseland': 4480, 'lisalundholm': 12506, 'torweijden': 21514, '107min': 7, '1921': 98, 'bernhardgoetzk': 2962, 'lildagov': 12398, 'walterjanssen': 22419, 'hanssternberg': 7957, '97min': 322, 'dorothygish': 5517, 'josephschildkraut': 10405, 'franklose': 6782, '150min': 51, 'mysteri': 15184, 'rudolfklein': 18487, 'rogg': 18267, 'audegede': 2468, 'nissen': 15903, 'gertrudewelck': 7275, 'alfredabel': 1140, '242min': 246, '1922': 99, 'documentari': 5382, 'benjaminchristensen': 2893, 'elisabethchristensen': 5867, 'marenpedersen': 13354, 'clarapontoppidan': 4342, '91min': 316, 'maxschreck': 14070, 'alexandergranach': 1060, 'gustavvonwangenheim': 7718, 'gretaschröd': 7608, '94min': 319, 'léonmathot': 12888, 'ginamanè': 7357, 'edmondvandaël': 5672, 'claudebenedict': 4354, '87min': 312, '1923': 100, 'patsyruthmil': 16532, 'normankerri': 15999, 'katelest': 11094, '133min': 33, 'gabrieldegravon': 6963, 'pierremagni': 16976, 'georgestérof': 7217, '417min': 290, 'comedi': 4472, 'haroldlloyd': 8009, 'jobynaralston': 10030, 'richarddaniel': 17932, 'carltongriffin': 3683, '1924': 101, 'normashear': 16003, 'johngilbert': 10148, 'ruthk': 18551, '95min': 320, 'jaquecatelain': 9486, 'léonidwalterdemalt': 12887, 'philippehériat': 16894, 'fredkellerman': 6873, '135min': 35, 'georgeo': 7193, 'brien': 3412, 'madgebellami': 12933, 'charlesedwardbul': 3948, 'cyrilchadwick': 4605, 'emiljan': 6020, 'malydelschaft': 13133, 'maxhil': 14051, 'emiliekurz': 6011, '88min': 313, 'erwinbiswang': 6234, 'margareteschön': 13364, 'gertrudarnold': 7274, 'theodorloo': 21165, 'hanscarlmuel': 7944, '129min': 29, 'paulricht': 16640, '143min': 43, 'enidbennett': 6098, 'ramonnovarro': 17554, 'wallacebeeri': 22398, 'frankcurri': 6766, '81min': 306, 'grigoriyaleksandrov': 7622, 'maksimshtraukh': 13092, 'mikhailgomorov': 14594, 'ivanov': 9057, '82min': 307, '1925': 102, 'famili': 6427, 'douglasfairbank': 5534, 'julannejohnston': 10590, 'snitzedward': 20003, 'charlesbelch': 3932, '155min': 56, 'renéeadoré': 17839, 'hobartbosworth': 8398, 'clairemcdowel': 4329, '151min': 52, 'charleschaplin': 3940, 'mackswain': 12915, 'tommurray': 21427, 'henrybergman': 8236, 'malcolmwait': 13113, 'georgiahal': 7224, 'western': 22504, 'gibsongowland': 7321, 'zasupitt': 23204, 'jeanhersholt': 9634, 'daleful': 4658, '140min': 40, 'irenerich': 8874, 'maymcavoy': 14093, 'bertlytel': 2977, 'ronaldcolman': 18341, '120min': 20, 'buckjon': 3500, 'virginiamarshal': 22208, 'edythechapman': 5732, '85min': 310, 'maemurray': 12968, 'royd': 18458, 'arci': 2185, 'josephinecrowel': 10394, '137min': 37, 'maryphilbin': 13830, 'arthuredmundcarew': 2294, '93min': 318, 'bellebennett': 2856, 'alicejoyc': 1178, '110min': 10, 'maebusch': 12965, 'mattmoor': 14005, 'victormclaglen': 22031, '86min': 311, 'lyadeputti': 12823, 'warwickward': 22451, '104min': 4, 'jeanforest': 9629, 'victorvina': 22042, 'pierrettehouyez': 16987, 'jeannemarie': 9653, 'laur': 12016, '114min': 14, 'francisx': 6740, 'bushman': 3534, 'bettybronson': 3001, 'georgehassel': 7181, '1926': 103, 'göstaekman': 7792, 'camillahorn': 3593, 'fridarichard': 6889, 'gretagarbo': 7601, 'larshanson': 12004, 'barbarak': 2732, '112min': 12, 'junetripp': 10700, 'ivornovello': 9076, 'marieault': 13509, 'arthurchesney': 2292, '92min': 317, '1927': 104, 'verabaranovskaya': 21956, 'nikolaybatalov': 15791, 'aleksandrchistyakov': 976, 'annazemtsova': 1864, '89min': 314, 'sci': 19196, 'fi': 6595, 'brigittehelm': 3419, 'gustavfröhlich': 7706, '153min': 54, 'henryb': 8235, 'walthal': 22428, 'karldan': 11028, '115min': 15, 'marypickford': 13831, 'roystewart': 18465, 'marylouisemil': 13824, 'gustavvonseyffertitz': 7717, '109min': 9, 'oliveborden': 16134, 'loutellegen': 12669, 'tomsantschi': 21456, 'phyllishav': 16931, 'victorvarconi': 22041, 'virginiabradford': 22200, 'robertedeson': 18110, '105min': 5, 'lyubovnenasheva': 12849, 'pyotrzinovyev': 17248, 'yelenayegorova': 22784, 'mikhailgipsi': 14592, '1935': 113, 'walterjam': 22418, 'leowilli': 12290, 'biographi': 3152, 'josephstrik': 10407, 'warner': 22442, 'dorothycum': 5514, 'ernesttorr': 6208, 'jamesneil': 9334, '160min': 61, 'ivanchuvelyov': 9031, 'vladimirobolenski': 22291, 'édithjéhann': 23401, 'unohen': 21720, 'fritzrasp': 6903, 'albertdieudonné': 902, 'vladimirroudenko': 22297, 'alexandrekoubitzki': 1081, '330min': 278, 'borislivanov': 3285, 'nikolaypopov': 15799, 'vasilinikandrov': 21898, 'layaschenko': 12091, '142min': 42, 'janetgaynor': 9416, 'charlesfarrel': 3949, 'benbard': 2866, 'albertgran': 906, '106min': 6, 'margaretlivingston': 13371, 'bodilros': 3232, 'vladimirfogel': 22276, 'lyudmilasemyonova': 12860, 'leonidyurenev': 12272, 'clarabow': 4339, 'charles': 3929, 'buddy': 3506, 'rog': 18248, 'richardarlen': 17912, '144min': 45, 'roscoekarn': 18402, 'louisebrook': 12629, 'bobperri': 3226, '84min': 309, '1928': 105, 'fritzkortn': 6902, 'francisleder': 6738, 'carlgoetz': 3636, '1929': 106, 'eleanorboardman': 5795, 'jamesmurray': 9330, 'bertroach': 2982, 'estelleclark': 6260, '98min': 323, 'jameshal': 9314, 'margaretmann': 13373, 'charlesmorton': 3961, 'bushmanjr': 3535, '100min': 0, 'evelynbr': 6341, 'williampowel': 22564, 'jackraymond': 9148, 'conradveidt': 4491, 'juliusmolnar': 10687, 'olgabaclanova': 16111, 'conradnagel': 4490, 'albertpollet': 918, '96min': 321, 'mariafalconetti': 13423, 'eugenesilvain': 6298, 'andréberley': 1633, 'mauriceschutz': 14033, 'lionelbarrymor': 12487, 'blanchefriderici': 3196, 'charleslan': 3956, 'florencemidgley': 6649, 'mariondavi': 13608, 'williamhain': 22556, 'dellhenderson': 5071, 'paulral': 16637, '83min': 308, 'annchristi': 1866, 'bertwoodruff': 2984, 'baberuth': 2623, 'gerdamaurus': 7256, 'willyfritsch': 22588, 'liendey': 12378, 'nataliekingston': 15430, 'henryarmetta': 8233, '102min': 2, 'brianahern': 3378, 'elissalandi': 5888, 'cyrilmclaglen': 4607, 'norahbar': 15971, 'erichvonstroheim': 6165, 'faywray': 6500, 'matthewbetz': 13976, '113min': 13, 'montagulov': 15009, 'marieglori': 13524, 'pierrealcov': 16943, 'yvetteguilbert': 23089, '195min': 140, 'albertsteinrück': 923, 'elsehel': 5963, 'bettyamann': 2999, 'klauspohl': 11596, '156min': 57, 'guinn': 7664, 'bigboy': 3083, 'william': 22542, 'paulfix': 16583, 'alexandraschmitt': 1077, 'holmeszimmermann': 8414, 'ilsetrautschold': 8745, 'gerhardbienert': 7258, '121min': 21, 'davidgutman': 4921, 'yelenakuzmina': 22783, 'andreikostrichkin': 1563, 'sofiyamagaril': 20016, 'maryduncan': 13812, 'ivanlinow': 9051, 'marfalapkina': 13356, 'ivanin': 9042, 'konstantinvasilyev': 11642, 'vasilibuzenkov': 21894, 'josefrovenský': 10376, 'edithmeinhard': 5664, 'gustavdiessl': 7704, 'leniriefenstahl': 12224, 'ernstpetersen': 6218, 'ernstudet': 6220, 'music': 15151, 'colleenmoor': 4465, 'neilhamilton': 15590, 'johnst': 10242, 'poli': 17034, 'lewayr': 12336, 'louiswolheim': 12659, 'johnwray': 10261, 'arnoldluci': 2263, '152min': 53, '1930': 108, 'grouchomarx': 7625, 'harpomarx': 8011, 'chicomarx': 4067, 'ditaparlo': 5346, 'ginettemaddi': 7364, 'andréebrab': 1637, 'mireillebarsac': 14779, 'marlenedietrich': 13710, 'kurtgerron': 11816, 'rosavaletti': 18398, 'hansadalbertschlettow': 7941, 'anthonyasquith': 1968, 'benlyon': 2904, 'jeanharlow': 9633, 'johndarrow': 10128, '127min': 27, 'sport': 20183, 'jackiecoop': 9128, 'roscoeat': 18401, '1931': 109, 'michelsimon': 14474, 'janiemarès': 9440, 'georgesflam': 7206, 'rogergaillard': 18255, 'virginiacherril': 22202, 'florencele': 6646, 'harrymy': 8037, 'maxbarwyn': 14044, 'warneroland': 22444, 'lewcodi': 12337, 'barrynorton': 2781, 'rudolfforst': 18484, 'lottelenya': 12611, 'carolaneh': 3710, 'reinholdschünzel': 17777, 'edwardg': 5713, 'robinson': 18209, 'marianmarsh': 13460, 'anthonybushel': 1972, 'fritzkamp': 6900, 'ernstbusch': 6214, 'elisabethwendt': 5879, 'peterlorr': 16814, 'ellenwidmann': 5937, 'ingelandgut': 8798, 'ottowernick': 16283, '117min': 17, 'raimu': 17412, 'pierrefresnay': 16970, 'fernandcharpin': 6565, 'alidarouff': 1190, '130min': 30, 'annabella': 1803, 'renélefèvr': 17847, 'jean': 9609, 'louisallibert': 12622, 'paulollivi': 16628, 'barbarastanwyck': 2744, 'davidmann': 4945, 'samhardi': 18837, 'berylmerc': 2985, 'dorotheawieck': 5512, 'herthathiel': 8284, 'emiliaunda': 6009, 'hedykrilla': 8128, 'jamescagney': 9288, 'edwardwood': 5725, 'joanblondel': 9986, 'johnbol': 10105, 'genevievetobin': 7139, 'loiswilson': 12565, 'raymondhackett': 17684, 'annechevali': 1879, 'matahi': 13936, 'hitu': 8390, 'billbambridg': 3093, 'maeclark': 12966, 'douglassmontgomeri': 5539, 'dorislloyd': 5499, 'frederickkerr': 6870, 'raymondcordi': 17683, 'henrimarchand': 8225, 'rollafr': 18314, 'marcellehainia': 13311, 'sévérinelerczinska': 20761, 'jeangehret': 9631, '1932': 110, 'pierreblanchar': 16955, 'gabrielgabrio': 6968, 'charlesvanel': 3965, 'raymondaimo': 17680, 'fredricmarch': 6876, 'miriamhopkin': 14787, 'rosehobart': 18410, 'holmesherbert': 8412, 'oranedemazi': 16218, 'johnbarrymor': 10101, 'joancrawford': 9990, 'film': 6613, 'noir': 15951, 'paulmuni': 16619, 'glendafarrel': 7453, 'helenvinson': 8183, 'noelfranc': 15947, 'mauricechevali': 14024, 'jeanettemacdonald': 9627, 'charlesruggl': 3962, 'charlesbutterworth': 3939, 'warrenwilliam': 22449, 'sidneyfox': 19831, 'alinemacmahon': 1212, 'harrybaur': 8024, 'robertlynen': 18143, 'louisgauthi': 12641, 'simoneaubri': 19885, 'clarkgabl': 4351, 'generaymond': 7136, 'maryastor': 13806, 'anndvorak': 1868, 'karenmorley': 11000, 'osgoodperkin': 16255, 'lawrencegr': 12081, 'clivebrook': 4430, 'annamaywong': 1839, 'eugenepallett': 6297, 'verreeteasdal': 21984, 'maureeno': 14019, 'sullivan': 20501, 'gregoryratoff': 7598, 'anitapag': 1758, '99min': 324, 'thomybourdell': 21228, '122min': 22, '1933': 111, 'kayfranc': 11196, 'herbertmarshal': 8263, 'tatsuosaitô': 20993, 'tomioaoki': 21418, 'mitsukoyoshikawa': 14847, 'hideosugawara': 8311, 'vascosantana': 21890, 'beatrizcosta': 2833, 'antóniosilva': 2088, 'teresagom': 21084, 'alfredodeldiestro': 1151, 'carmenguerrero': 3697, 'antonior': 2062, 'frausto': 6850, 'luisg': 12761, 'barreiro': 2766, '1934': 112, 'bebedaniel': 2837, 'doriskenyon': 5498, 'isabeljewel': 8940, 'takeshisakamoto': 20844, 'nobukofushimi': 15938, 'denôhinata': 5130, 'chôkoiida': 4305, 'garycoop': 7055, 'edwardeveretthorton': 5710, 'mariedressl': 13520, '111min': 11, 'rubykeel': 18477, 'dickpowel': 5244, 'warnerbaxt': 22443, 'georgebr': 7167, 'robertarmstrong': 18091, 'brucecabot': 3455, 'frankreich': 6793, 'nedspark': 15556, 'mayrobson': 14096, 'guykibbe': 7730, 'wolfgangliebenein': 22616, 'carlesmond': 3635, 'magdaschneid': 12979, 'luiseullrich': 12760, 'katharinehepburn': 11109, 'joanbennett': 9985, 'paulluka': 16610, 'ednamayoliv': 5679, 'margaretsullavan': 13376, 'billieburk': 3104, 'henriettacrosman': 8211, 'heatherangel': 8113, 'normanfost': 15997, 'lucillelavern': 12716, 'iankeith': 8634, 'lewisston': 12343, 'tokihikookada': 21370, 'ichirôsugai': 8661, 'bontarômiak': 3264, 'kumekourab': 11787, 'fernandel': 6566, 'henripoupon': 8227, 'jeanservai': 9664, 'jeandasté': 9618, 'gillesmargar': 7350, 'louislefebvr': 12647, 'shirleytempl': 19683, 'jamesdunn': 9299, 'janedarwel': 9401, 'judithallen': 10560, 'robertdonat': 18107, 'louiscalhern': 12626, 'sidneyblackm': 19829, 'fredastair': 6854, 'gingerrog': 7366, 'alicebradi': 1171, 'mariebel': 13511, 'pierrerichard': 16982, 'willm': 22579, 'georgespitoëff': 7213, 'claudettecolbert': 4382, 'rochellehudson': 18223, 'jamesonthoma': 9338, 'walterconnolli': 22411, 'alanhal': 872, 'catherinedoucet': 3781, 'paulawess': 16556, 'antonwalbrook': 2076, 'olgatschechowa': 16125, 'hansmos': 7955, 'marcelvallé': 13325, 'paulazaï': 16557, 'maxdear': 14049, '279min': 268, 'gavingordon': 7094, 'johnlodg': 10183, 'samjaff': 18853, 'louisedress': 12631, 'aubreysmith': 2467, 'lesliehoward': 12307, 'merleoberon': 14247, 'raymondmassey': 17686, 'nigelbruc': 15737, 'isamiranda': 8963, 'memobenassi': 14227, 'tatyanapavlova': 21011, 'friedrichbenf': 6892, 'johnnyweissmul': 10212, 'paulcavanagh': 16569, 'myrnaloy': 15181, 'natpendleton': 15490, 'charlesblavett': 3936, 'celiamontalván': 3835, 'jennyhélia': 9754, 'édouarddelmont': 23402, 'carolelombard': 3717, 'reikôtani': 17770, 'kôjimitsui': 11886, 'emikoyagumo': 5996, 'yoshikotsubouchi': 22898, 'madeleinecarrol': 12923, 'luciemannheim': 12707, 'godfreytearl': 7487, 'errolflynn': 6227, 'oliviadehavilland': 16152, 'lionelatwil': 12486, 'basilrathbon': 2804, '119min': 19, 'freddiebartholomew': 6859, 'franklawton': 6778, 'elizabethallan': 5891, 'frankmorgan': 6787, 'reginaldowen': 17752, 'prestonfost': 17175, 'margotgraham': 13395, 'françoiserosay': 6837, 'andréalerm': 1631, 'jeanmurat': 9644, 'louisjouvet': 12645, 'charleslaughton': 3957, 'cedrichardwick': 3829, '108min': 8, 'franchotton': 6719, 'herbertmundin': 8264, '132min': 32, 'kittycarlisl': 11573, 'maryboland': 13808, '128min': 28, 'sôjikiyokawa': 20764, 'denjirôôkôchi': 5114, 'kiyozo': 11584, 'kunitarôsawamura': 11809, 'reizaburôyamamoto': 17782, 'minorutakas': 14748, 'erikrhod': 6188, '101min': 1, 'jeanarthur': 9611, 'arthurhohl': 2298, 'jamesdonlan': 9297, 'domingosol': 5406, 'manueltamé': 13263, 'ramónvallarino': 17568, '1936': 114, 'jamesstewart': 9347, 'jeangabin': 9630, 'suzyprim': 20663, 'janyholt': 9483, 'vivianerom': 22258, '168min': 69, 'walterhuston': 22416, 'ruthchatterton': 18546, 'pierreaumont': 16945, '1937': 115, 'sylviasidney': 20732, 'spencertraci': 20176, 'walterabel': 22406, 'shin': 19642, 'ichihimori': 8655, 'masaohayama': 13891, 'dolorescostello': 5394, 'zitaperczel': 23289, 'ellagombaszögi': 5918, 'kláritolnay': 11601, 'jenötörz': 9766, 'alernestgarcia': 1033, 'paulettegoddard': 16582, 'tinysandford': 21331, 'chesterconklin': 4038, 'hankmann': 7916, 'stanleyblyston': 20273, 'douglassdumbrill': 5537, 'georgebancroft': 7164, 'lionelstand': 12489, 'gailpatrick': 6994, 'humphreybogart': 8555, 'bettedavi': 2998, 'heggi': 8136, 'gloriastuart': 7479, 'claudegillingwat': 4365, 'arthurbyron': 2290, 'nan': 15314, 'jackholt': 9124, 'irenedunn': 8869, 'allanjon': 1253, 'charleswinning': 3966, 'paulrobeson': 16642, 'josephinehutchinson': 10396, 'anitalouis': 1756, 'donaldwood': 5441, 'victormoor': 22032, 'helenbroderick': 8175, '103min': 3, 'joelmccrea': 10059, 'chestermorri': 4039, 'walterbrennan': 22408, 'irenehervey': 8871, 'melvyndougla': 14226, 'carygr': 3758, 'ralphbellami': 17507, 'alexanderd': 1056, 'hugohaa': 8529, 'bedrichkaren': 2838, 'zdenekstepánek': 23216, 'václavvydra': 22363, 'roberttaylor': 18189, 'ianhunt': 8631, 'janebryan': 9398, 'wendybarri': 22482, 'edwardarnold': 5701, 'raymilland': 17679, 'luisalberni': 12750, 'niallmacginni': 15644, 'bellechrystal': 2857, 'johnlauri': 10178, 'ericberri': 6153, 'luiserain': 12757, 'tillylosch': 21273, '138min': 38, 'mireillebalin': 14778, 'pierreetchepar': 16967, 'margueritemoreno': 13402, 'arthurtreach': 2309, 'helenwestley': 8186, 'charlesboy': 3937, 'leocarrillo': 12233, 'colincl': 4459, 'ericblor': 6154, 'patricknowl': 16514, 'waynemorri': 22458, 'galesondergaard': 7005, 'gloriaholden': 7475, '116min': 16, 'janewyatt': 9425, 'johnhoward': 10162, 'beulahbondi': 3009, 'faybaint': 6495, 'thomasmitchel': 21217, 'nelsoneddi': 15612, 'hermanb': 8271, 'randolphscott': 17577, '1940': 119, 'robertmontgomeri': 18148, 'rosalindrussel': 18381, 'maywhitti': 14106, 'alanmarsh': 879, 'sukezôsukedakaya': 20486, 'chôjûrôkawarasaki': 4304, 'kan': 10915, 'emonnakamura': 6077, 'tsuruzônakamura': 21596, 'chôemonbandô': 4302, 'willhay': 22541, 'mooremarriott': 15021, 'grahammoffatt': 7572, 'sebastiansmith': 19255, 'clauderain': 4379, 'henrystephenson': 8249, 'bartonmaclan': 2789, '118min': 18, 'saturninfabr': 19145, 'anim': 1737, 'adrianacaselotti': 586, 'harrystockwel': 8040, 'royatwel': 18452, 'adolphemenjou': 576, 'anneshirley': 1898, 'barbarao': 2738, 'neil': 15587, 'gloriadickson': 7472, 'edwardnorri': 5720, 'ottokrug': 16280, 'constancebennett': 4492, 'rolandyoung': 18308, 'williamgargan': 22553, 'henryfonda': 8240, 'jeandixon': 9622, 'madeleinerenaud': 12925, 'marcellegéniat': 13310, '1938': 116, 'nikolaycherkasov': 15793, 'nikolaiokhlopkov': 15780, 'andreiabrikosov': 1560, 'dmitriyorlov': 5374, 'pato': 16473, 'annsheridan': 1936, 'davidniven': 4955, 'mickeyrooney': 14503, 'henryhul': 8242, 'lesliefenton': 12304, 'waltercatlett': 22409, 'juliencarett': 10650, 'simonesimon': 19891, 'fernandledoux': 6568, 'alekseilyarski': 1006, 'varvaramassalitinova': 21885, 'mikhailtroyanovskiy': 14608, 'elizavetaalekseeva': 5914, 'armandbernard': 2246, 'aiméclariond': 751, 'ginetteleclerc': 7363, 'robertvatti': 18193, 'dorisnolan': 5501, 'arletti': 2242, 'margaretlindsay': 13370, 'margaretlockwood': 13372, 'michaelredgrav': 14385, 'tyronepow': 21643, 'robertmorley': 18149, '149min': 50, 'alanmowbray': 880, 'albertpréjean': 919, 'gabrielledorziat': 6978, 'eugeniuszbodo': 6301, 'józeforwid': 10789, 'helenagrossówna': 8164, 'ludwiksempolinski': 12736, 'wendyhil': 22486, 'wilfridlawson': 22525, 'marielohr': 13533, 'michèlemorgan': 14498, 'pierrebrasseur': 16958, 'léonbelièr': 12885, '126min': 26, 'douglasfairbanksjr': 5535, 'idalupino': 8672, '1939': 117, 'virginiagrey': 22206, 'glennislorim': 7465, 'charlescoburn': 3943, 'frankalbertson': 6761, 'robertpreston': 18175, 'briandonlevi': 3390, 'geraldinefitzgerald': 7245, 'mischaauer': 14819, 'georgeraft': 7195, 'victorfrancen': 22020, 'madeleineozeray': 12924, 'johnclement': 10122, 'ralphrichardson': 17513, 'juneduprez': 10694, 'dianawynyard': 5227, 'frankpettingel': 6791, 'cathleencordel': 3798, 'vivienleigh': 22264, '238min': 242, 'greergarson': 7584, 'terrykilburn': 21104, 'johnmil': 10203, 'joanfontain': 9994, 'hara': 7975, 'jacquelinelaur': 9182, 'julesberri': 10594, 'mariaouspenskaya': 13483, 'leebowman': 12125, 'donamech': 5443, 'inaclair': 8770, 'belalugosi': 2851, 'lonchaneyjr': 12579, 'burgessmeredith': 3524, 'bettyfield': 3004, 'charlesbickford': 3935, 'unamerkel': 21712, 'ritahayworth': 18049, 'priscillalan': 17186, 'gladysgeorg': 7448, 'marceldalio': 13301, 'noragregor': 15970, 'paulettedubost': 16581, 'milaparéli': 14652, 'edwigefeuillèr': 5727, 'georgerigaud': 7197, 'daniellecourtoi': 4758, 'madyberri': 12962, 'johnwayn': 10257, 'clairetrevor': 4335, 'andydevin': 1656, 'johncarradin': 10112, 'judygarland': 10578, 'raybolg': 17674, 'bertlahr': 2976, 'laurenceolivi': 12055, 'florarobson': 6640, 'marjorieweav': 13661, 'arleenwhelan': 2238, 'shôtarôhanayagi': 19791, 'kôkichitakada': 11893, 'ryôtarôkawanami': 18608, 'kinnosuketakamatsu': 11522, 'reedhadley': 17734, 'sheiladarci': 19579, 'williamcorson': 22545, 'leanderdecordova': 12105, 'genelockhart': 7135, 'ruthgordon': 18547, 'maryhoward': 13816, 'cantinfla': 3616, 'joaquínpardavé': 10027, 'saragarcía': 19036, 'sofíaálvarez': 20018, 'jeffreylynn': 9699, '141min': 41, 'eleanorpowel': 5800, 'georgemurphi': 7192, 'arthurkennedi': 2301, 'coreyburton': 4513, 'larained

In [50]:
#Distance d'un film avec tous les autres films
similarity = cosine_similarity(vector_matrix)

In [51]:
similarity.shape

(12322, 12322)

In [52]:
#Première ligne de la matrice de similarité, qui représente la similarité cosinus entre le premier film et tous les autres films
similarity[0]

array([1.        , 0.09090909, 0.10660036, ..., 0.15075567, 0.10660036,
       0.15075567])

In [53]:
#Matrice similarity
similarity

array([[1.        , 0.09090909, 0.10660036, ..., 0.15075567, 0.10660036,
        0.15075567],
       [0.09090909, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.10660036, 0.        , 1.        , ..., 0.1767767 , 0.125     ,
        0.1767767 ],
       ...,
       [0.15075567, 0.        , 0.1767767 , ..., 1.        , 0.1767767 ,
        0.75      ],
       [0.10660036, 0.        , 0.125     , ..., 0.1767767 , 1.        ,
        0.1767767 ],
       [0.15075567, 0.        , 0.1767767 , ..., 0.75      , 0.1767767 ,
        1.        ]])

# Fonction de recommandation

In [65]:
def recommandation(movie):
    # Votre code pour obtenir les recommandations de films
    # Rechercher le film en fonction de primaryTitle, originalTitle ou frenchTitle
    movie_index = new_data[(new_data['primaryTitle'] == movie) | 
                           (new_data['originalTitle'] == movie) | 
                           (new_data['French_Title'] == movie)].index[0]
    # Extraire les distances du film donné avec tous les autres films
    distances = similarity[movie_index]
    # Trouver les 5 films les plus similaires excepté du film donné 
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    # Créer une liste pour stocker les données des films recommandés
    recommendations_data = []
    
    for i in movies_list:
        title = new_data.iloc[i[0]]['primaryTitle']
        distance = i[1]
        tconst = new_data.iloc[i[0]]['tconst']
        
        # Ajouter les données du film recommandé à la liste
        recommendations_data.append({'tconst': tconst,'Film': title, 'Similarity': distance})
    
    # Créer un DataFrame à partir de la liste des données des films recommandés
    recommendations_df = pd.DataFrame(recommendations_data)
    
    return recommendations_df

In [66]:
# Appel de la fonction recommandation avec un exemple de film
movie_recs_df = recommandation("X-Men (2000)")
# Affichage du DataFrame contenant les recommandations de films
print(movie_recs_df)

      tconst                               Film  Similarity
0  tt1877832  X-Men: Days of Future Past (2014)         0.7
1  tt0290334                          X2 (2003)         0.6
2  tt3315342                       Logan (2017)         0.5
3  tt0078346                    Superman (1978)         0.4
4  tt0082694            The Road Warrior (1981)         0.4

In [70]:
movie_recs_df['tconst']

0    tt1877832
1    tt0290334
2    tt3315342
3    tt0078346
4    tt0082694
Name: tconst, dtype: object